apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.loadbalancer.meta_name }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.loadbalancer.ports.port }}
      targetPort: {{ .Values.loadbalancer.ports.targetport }}
  selector:
    component: {{ .Values.deployment.component }}