apiVersion: v1
kind: ServiceAccount
metadata:
 name: {{ .Values.rbac.service_account_name }}
 namespace: {{ .Values.namespace.name }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind:  ClusterRole
metadata:
  name: {{ .Values.rbac.cluster_role_name}}
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods" ]
  verbs: ["*"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["*"]
- nonResourceURLs: ["/metrics"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.cluster_rolebinding_name}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.cluster_role_name}}
subjects: 
  - kind: ServiceAccount
    name: {{ .Values.rbac.service_account_name}}
    namespace: {{ .Values.namespace.name }}