orbs:
  aws-eks: circleci/aws-eks@0.2.3
version: 2.1
workflows:
  deployment:
    jobs:          
      - aws-eks/install-helm-chart:
          chart: stable/hello-world-ui
          cluster-name: Dev
          release-name: wordpress-release
          aws-region: '${AWS_REGION}'
          aws-profile: arn:aws:iam::066459049511:instance-profile/Dev-EKSClusterIAM-QXN7S9W1J1P6-EksInstanceProfile-1AAROOYCOLBLM