orbs:
  aws-eks: circleci/aws-eks@0.2.3
version: 2.1
workflows:
  deployment:
    jobs:          
      - aws-eks/install-helm-chart:
          chart: stable/hello-world-ui
          cluster-name: Dev
          release-name: wordpress-release
          aws-region: '${AWS_REGION}'
          version: v3.1.2