orbs:
  aws-eks: circleci/aws-eks@0.2.3
  helm: circleci/helm@0.1.1
version: 2.1
workflows:
  install-helm-on-clinet:
    parameters:
      version: v3.1.2
         
  deployment:  
    jobs:         
      - aws-eks/install-helm-chart:
          chart: stable/hello-world-ui
          cluster-name: Dev
          release-name: wordpress-release
          aws-region: '${AWS_REGION}'