orbs:
  aws-eks: circleci/aws-eks@0.2.3
  helm: circleci/helm@0.1.1
version: 2.1
workflows:
  deployment:
    jobs:          
      - install-helm-client:
          version: v3.1.2

      - aws-eks/install-helm-chart:
          chart: stable/hello-world-ui
          cluster-name: Dev
          release-name: wordpress-release
          aws-region: '${AWS_REGION}'